#!/bin/bash

echo "Installing dependencies..."
#Check if its installed

#If not installed
	pip install mdtraj #PDBtoFIle
	pip install biopython pandas #site_identifier.py
	sudo apt install dssp
	pip install ProDy






conda create --name pocketseeker python=3.10

conda activate pocketseeker

pip install mdtraj biopython pandas



