channels:
  - salilab
  - conda-forge
  - bioconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - pip=25.0.1
  - python=3.11.0
  - blast=2.14.0
  - pip:
      - biopython==1.85
      - mdtraj==1.10.3
      - numpy==2.2.3
      - pandas==2.2.3
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - requests==2.32.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - sklearn-compat==0.1.3